### ISSUE TITLE
Lack of a license

### ISSUE THREAD

**Issue by bminusl** [thanhvg/emacs-hnreader#2]
I maintain an [awesome](https://github.com/topics/awesome) list named [awesome-hackernews](https://github.com/bminusl/awesome-hackernews) where Hacker News related tools are featured.

I noticed `emacs-hnreader` does not have a license. See [https://choosealicense.com/no-permission/](https://choosealicense.com/no-permission/).

Is this an oversight?

**Comment by thanhvg** [comment]
It's GPL3, GPL3 ceremony is placed on top of the el file:
https://github.com/thanhvg/emacs-hnreader/blob/master/hnreader.el

**Comment by bminusl** [comment]
Ok, I missed it.

Usually a `LICENSE` or` COPYING` file is defined.
