### ISSUE TITLE
Can we have a link to open the comments page in eww/external browser?

### ISSUE THREAD

**Issue by gabrielhidasy** [thanhvg/emacs-hnreader#4]
This package is awesome, but sometimes I want to comment on stuff. I imagine supporting that directly in emacs will be a lot of work, but what about adding an extra link to open the comments in eww/external browsers?

I modded `hnreader--print-frontpage-item` with `(insert (format "[[%s][%s]]\n" url "View comments in browser"))` and 
`(defun hnreader--print-comments` with `(insert (format "\n* [[%s][Open comments in browser]]" url))` which works for me,
but I think the ideal solution would be to make this configurable, and ideally put a direct link to each comment in the comments page instead of just the generic go to comment link.

**Comment by thanhvg** [comment]
Do you want to have a reply link at the bottom of each comment?

**Comment by gabrielhidasy** [comment]
That would be ideal for me, but a single link on the bottom of the page to get to the comments page would be good enough.

It's not clean elisp, but I added the changes (with the per-comment reply link) in this gist:
https://gist.github.com/gabrielhidasy/41f425aad16a2cf1f28e88f036b29e71

**Comment by thanhvg** [comment]
Oh so currently 

``` org
#+STARTUP: overview indent
#+TITLE: Inside the Proton
https://www.quantamagazine.org/inside-the-proton-the-most-complicated-thing-imaginable-20221019/
[view story in eww]
410 points | by shantanu_sharma | 151 comments


// comments
```

You want me to add the link to the comment page

``` org
#+STARTUP: overview indent
#+TITLE: Inside the Proton
https://www.quantamagazine.org/inside-the-proton-the-most-complicated-thing-imaginable-20221019/
[view story in eww]
https://news.ycombinator.com/item?id=33262637 <=== it this what you want?
410 points | by shantanu_sharma | 151 comments


// comments
```

**Comment by gabrielhidasy** [comment]
I'm thinking more of a per-comment link, so a comment page would look like this

```
#+STARTUP: overview indent
#+TITLE: Show HN: A new search engine UX I've been working on in my free time
https://swurl.com/?q=Paul+Graham+y+combinator
[[eww:https://swurl.com/?q=Paul+Graham+y+combinator][view story in eww]]
520 points | by ryes | 297 comments

* idk1
Well that is shockingly good! I was not expecting somthing so good. Nice job! I...

[[https://news.ycombinator.com/reply?id=33260043&goto=item%3Fid%3D33251954%2333260043][reply]] [[eww:https://news.ycombinator.com/reply?id=33260043&goto=item%3Fid%3D33251954%2333260043][reply on eww]]

** codegeek
I agree. It is really good. But I also want the ability to select my sources...

[[https://news.ycombinator.com/reply?id=33263928&goto=item%3Fid%3D33251954%2333263928][reply]] [[eww:https://news.ycombinator.com/reply?id=33263928&goto=item%3Fid%3D33251954%2333263928][reply on eww]]
```

But adding the link as you did on your example also works, it's just a bit more work to get back to the comment I intend to reply to and looks a bit cleaner for reading

**Comment by thanhvg** [comment]
will implement this feature when time allows :(

**Comment by thanhvg** [comment]
added reply, let me know what you think
