### ISSUE TITLE
Open comments in same window

### ISSUE THREAD

**Issue by butter-radish** [thanhvg/emacs-hnreader#9]
Trying to get comments to open in the same window when run from a function:

```
  (defun my/hnreader-view-comments (url)
    (setq-local hnreader-view-comments-in-same-window t)
    (hnreader-comment url))
```

But it's not working. I'm very new to writing Elisp, I might be making an obvious error; sorry if that's the case.

**Comment by thanhvg** [comment]
Try this

``` elisp
(defun my/hnreader-view-comments (url)
  (let ((hnreader-view-comments-in-same-window t))
    (hnreader-comment url)))
```

**Comment by butter-radish** [comment]
That does work, thanks so much! <3

**Comment by butter-radish** [comment]
Actually, thanhvg, your code doesn't work—I stupidly tried it out with only window open, before I closed the issue. It still has the old unwanted behaviour of opening the HNComments buffer in the other window when I have two or more windows open. Sorry for not testing it properly, but does this mean this is a bug?

**Comment by thanhvg** [comment]
Not a bug, but the description of the variable `hnreader-view-comments-in-same-window` is wrong https://github.com/thanhvg/emacs-hnreader/blob/master/hnreader.el#L76. And by default it is set to `t` already. I will fix the description in the future.

When `hnreader-view-comments-in-same-window` is non nil then the comments will be showed in the window which has been showing the comments, not creating a new window (https://github.com/thanhvg/emacs-hnreader/blob/master/hnreader.el#L139-L142). So if you already have a window showing comment page, that window will be used again to show the new content in the comment buffer. 

It is designed that way to suit my taste. Once you have more than one window opened it will always show comments buffer in the other windows. So it is possible to see both front page and comment pages at the same time.

Here is how it is used https://github.com/thanhvg/emacs-hnreader/blob/master/hnreader.el#L139-L142

**Comment by butter-radish** [comment]
Ohhh, I see. Maybe that variable can be named `hnreader-view-comments-reuse-window` or `hnreader-view-comments-reuse-buffer` to be clearer. 

I'll figure out some way to get the behaviour I want, thanks!
